apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  bookmarks.yaml: |
    - Infra:
        - GitHub Homelab:
            - href: https://github.com/Alecho02/homelab
  services.yaml: |
    - Cluster:
        - Homepage:
            href: http://home.192.168.10.118.nip.io
            description: Portal principal del homelab
        - Headlamp:
            href: http://headlamp.192.168.10.118.nip.io
            description: Vista de pods, containers y servicios
    - Observabilidad:
        - Grafana:
            href: http://grafana.192.168.10.118.nip.io
            description: Dashboards y métricas
        - Prometheus:
            href: http://prometheus.192.168.10.118.nip.io
            description: Consultas y targets
        - Alertmanager:
            href: http://alertmanager.192.168.10.118.nip.io
            description: Estado y gestión de alertas
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
