apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  bookmarks.yaml: |
    - Infra:
        - GitHub Homelab:
            - href: https://github.com/Alecho02/homelab
  services.yaml: |
    - Cluster:
        - Grafana:
            href: http://monitoring-grafana.monitoring.svc.cluster.local
            description: Observabilidad interna
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
