apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  bookmarks.yaml: |
    - Infra:
        - GitHub Homelab:
            - href: https://github.com/Alecho02/homelab
  services.yaml: |
    - Media y Descargas:
        - Jellyfin:
            href: http://192.168.10.184:8899/web/#/home.html
            icon: jellyfin.png
            description: Media server
        - qBittorrent:
            href: http://192.168.10.184:8888/
            icon: qbittorrent.png
            description: Descargas
    - Red y DNS:
        - Pi-hole:
            href: http://192.168.10.90/admin/login
            icon: pi-hole.png
            description: DNS / ad-block
            widget:
              type: pihole
              url: http://192.168.10.90
              version: 6
              key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
        - Portainer:
            href: http://192.168.10.184:9000/#!/auth
            icon: portainer.png
            description: Gestión de contenedores en NAS
    - Observabilidad:
        - Grafana:
            href: http://grafana.192.168.10.118.nip.io
            icon: grafana.png
            description: Dashboards y métricas
        - Prometheus:
            href: http://prometheus.192.168.10.118.nip.io
            icon: prometheus.png
            description: Consultas y targets
        - Alertmanager:
            href: http://alertmanager.192.168.10.118.nip.io
            icon: prometheus.png
            description: Estado y gestión de alertas
    - Cluster:
        - Headlamp:
            href: http://headlamp.192.168.10.118.nip.io
            icon: kubernetes-dashboard.png
            description: Vista de pods, containers y servicios
        - Homepage:
            href: http://home.192.168.10.118.nip.io
            icon: homepage.png
            description: Portal principal del homelab
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
