apiVersion: v1
kind: Secret
metadata:
    name: homepage-pihole-widget
    namespace: homepage
type: Opaque
stringData:
    PIHOLE_API_KEY: ENC[AES256_GCM,data:vhQBvU1knYmhBZKSubGv5Fy3TXWolqn3DTwQbnSNMTsnsA052emDn/90Iu0=,iv:JgundcFDSnAl7VeOLLOFWXpuDlruRQtFCF963OUf8xg=,tag:MLc1++UZB9+x7+li1yZXhg==,type:str]
sops:
    age:
        - recipient: age1c26e9klyhrh6cgz8amnznuqc4k5y2gfh295fvnjx6mc388srresqsjrudj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcUw3L1FyN0dkYXppTkwx
            TityT1JmdUJBU3ZGTnBkZVkvUnAxVjJHNUM0CkhYSVIraTd6dThmZDZFTjVWRHNo
            T2UyUVR5a1E3WlhtcVFYajc2SEI4MncKLS0tIHRDQ1dqQjMxa2xFeCtLanVraHhn
            SmVmUVR2ZjZJQ09qU0UrbzdTd3pxTHMKN8cUpw6dHJC3KFgt7q4KPUBvrHHGicqk
            F0wN4kzjLxNHTL48PsPBUAz3KpaquONYglr15Cz//XSOc1++PXW2Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T21:27:31Z"
    mac: ENC[AES256_GCM,data:WQm3psuhGtBVXZvoK6d/jPGlvfJLFGkaNXMZdDcJ1lOmQ9jhfsKIkCrmx+3YbC7dQvh68KUQFoqZSp+QMP3uuET6rlw1I0tB7VBko08YkyQnv34rm2R4/bnlkKtx4Zlvd2Ywoet0Gs59SnI5srR9vcx5kgRFtNZ1TaKAgLbpTEI=,iv:2mX2n9o1BR2oq/hUvPQwBLnQrew2ntgBAgA/MolgWQM=,tag:Q/FymFgKniXFpJCRkVkr4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
