apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-auth
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:j7ZjWJEzwt1Oy5/3lgM5rimKTVZR0DBbqvRyxRk=,iv:ryPDiEUV8/aSYPVbnVWRouY05hyxuAyoWOyTdxjLgiE=,tag:3uxxDTjCVyWz8zCgiSVAeQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:YsdBE0vZ7APHMoydR966JCYlgNE1Iu5gg4B5jNHBV9o=,iv:NxTeMnwOYRLa5PZJBUABLJTXCbeRS4Pqz2mWM4b+Di0=,tag:pRq+znv4982KOQUuQa1b1w==,type:str]
sops:
    age:
        - recipient: age1c26e9klyhrh6cgz8amnznuqc4k5y2gfh295fvnjx6mc388srresqsjrudj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NlQ3K3NCVTMrNEZzSnhM
            TzVPR05pZFhNL2VVWFdSLzl1cnMyaXBtR1ZzCnZsMGVIM3FrWmozL1c1ZDBQaUlG
            UmVjdnhKaHRrcGt4eFVLYUtON0xLZkUKLS0tIGhKcDZ6QXVXY2k0ZUpZdERrbHhO
            VU0vQmdzR0E3YlZ0bklxYXFwdEthQW8K0nl0ymd0IdhbhYRUzXnDoLJB4nNqHogk
            l5buBH9KKiRpp/QGLDIc1ofuqvUdbxN/DRYIbE8JdCLkxm0pZfHdrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T22:34:49Z"
    mac: ENC[AES256_GCM,data:JdV3HtstSJ19tef7KwgzodSzGORydNe6oiX53E3vusPQ9fEFsP8VuAZFyS8woqxnFVgwWkvfpGkgvxATn/HXuwQrP42CTc+iUXehT9onLr8tYOmrCxJth2KyJQVS2ADKj6exohtR85AHrgA8HPv3AifHupXG90Yetgm/RDDcWq0=,iv:UBOqhRsMcDa7Uc53fyzCkrVThuXS3bUfIE95pqL7In4=,tag:db9GsCu5l7nNE1hEt6Spxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
