apiVersion: v1
kind: Secret
metadata:
    name: postgres-exporter-auth
    namespace: monitoring
type: Opaque
stringData:
    DATA_SOURCE_USER: ENC[AES256_GCM,data:6ICUjsn34u4p,iv:sFLCIcEHS/YywdjKgK9Kw9xK9Vb4kPb5YpP+gVtu3KQ=,tag:yD9TFfLV7X+QbgSb1PidhQ==,type:str]
    DATA_SOURCE_PASS: ENC[AES256_GCM,data:4o2EvWv/Cob/DnEyjUXC5DOw7T8we7L4rBo3J81iBmY=,iv:bMMVMcwNz2qkneb9aOsi78C1HCDxEo4ZCpc1l4FN61s=,tag:on2OuHGBYyaEBu61nbKq1A==,type:str]
sops:
    age:
        - recipient: age1c26e9klyhrh6cgz8amnznuqc4k5y2gfh295fvnjx6mc388srresqsjrudj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT2k3NjJrOFFJMGtTeEg0
            b0tyelZyelBVUWhpQWpTQmdZbyswWk9PQWhnCmNCNE02TVduOVJEVFl2eDZTS3ds
            cGlkaHByVUFWS2dYdSsySG56c1JQR1kKLS0tIHpXSm1iUXhSODQ4K2VPbFhJb0g5
            RlhLSGU3SHc3T09WOUYrVTNBZStmUjQK2LGBGvubSXED+AIKN8keDVn+/InO2gzx
            2tCox249W93jdol6r71nl0YfyH55sn92+NxJWJMqoXWcNuvc5Bc+Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T22:30:47Z"
    mac: ENC[AES256_GCM,data:0lTAhbx2AC54oWRNpE+YMYxMxjS3wpyiCWDbzaXzCS6CdU5dAL0yvPEETCtTDiMQtCOcs9RKDlvLYMkjqFdgGfrcCRxH+FygV+oD7J1zvq1vWiLgflUMbi5bxKb93MxDQA6Gr8mBBLS6LPvF/lYDgJhZyidjh0Ma8OecuDwEJnY=,iv:zDI2BFQbdtZRZPHXVnkGZ/7+THtzVWLk9duGmt8bfow=,tag:tN7MC2Y5fARSzp1N6lLvHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
