apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: data
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:OjKSGDfLCAJo,iv:oIppquq2ojv7W3P4f6ag4Y4pvdy2cEWEixiXYNwKeTI=,tag:TAKWf0glXI+WelkCePAXKw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qTW1DKeLrRIm1gG023c1aSfKfaLN6I8YFZuekJZ8RDo=,iv:9tzSYSajp0W6RRnMOIijzJkgPMRGIu4jJ5kRVxqUhu4=,tag:OBzNDKMcpn/sMRGf2ivMHA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:pOzsnXPGNy05,iv:t9LQOwR2U5yj1s/hnf96hTMWuh152v0/CeeZgEGejP0=,tag:jPLlhGpsmKLegT5B3gBGrA==,type:str]
sops:
    age:
        - recipient: age1c26e9klyhrh6cgz8amnznuqc4k5y2gfh295fvnjx6mc388srresqsjrudj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdUg3U2tOaVRxcTkrTmZY
            ZFNXU0grYVF1ZjdSRTF6bFY1VUtpM01kSXdZCnZTYTlWV0QwdmVGZ0NLMVBOZmFt
            Q2RYT011MFA5WmpuLy9hTStsYXQ1THcKLS0tIEpXaWRrUTF5a2lydno2ZmVnbDdq
            eldyLzdVRGZ2eTdPZkY5WVBKdmo4L1EKzMHihFOxf874XCmu98O+e6uZyYc4TGe0
            NBTFBuiygwTYKzpewkQk2ERdKVkJk22TLGnZ9h5MW2jts1RLXS19eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T22:30:47Z"
    mac: ENC[AES256_GCM,data:drUyP4v9Vkp3ZaPTlEdeTmGtlSZcm6QTro0evx9TsamLUuZSvs4wqHBqMZDM4nkkSQNVnZMBETXILjxHLagzq9/SIVL9V1RfAutTQUUtzHFlZnx6y6rjU9XTuXs6NzoZIq8CM1qlzrS5+7DnU43b0TsOB908/GXj6duNx/Auv74=,iv:22tIt0RsdCCW7voYewdssOyUWycdmFWoaauXAtvB3l8=,tag:TlGwg8pSzGEyUJ7t9fHP+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
