pipeline {
  agent any
  environment {
    REGISTRY = "ghcr.io/alecho02"
    IMAGE = "java17-vault-service"
    TAG = "\${env.BUILD_NUMBER}"
    VAULT_ADDR = "http://vault.vault.svc.cluster.local:8200"
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Read Secret From Vault') {
      steps {
        withCredentials([string(credentialsId: 'vault-root-token', variable: 'VAULT_TOKEN')]) {
          sh '''
            set -e
            SECRET_VALUE=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/secret/data/java17-vault-service | jq -r '.data.data.APP_SECRET')
            echo "$SECRET_VALUE" > vault_secret_value.txt
          '''
        }
      }
    }
    stage('Build Image') {
      steps {
        sh '''
          set -e
          docker build -t $REGISTRY/$IMAGE:$TAG -f training/java17-vault-service/Dockerfile training/java17-vault-service
        '''
      }
    }
    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'ghcr-credentials', usernameVariable: 'GH_USER', passwordVariable: 'GH_TOKEN')]) {
          sh '''
            set -e
            echo "$GH_TOKEN" | docker login ghcr.io -u "$GH_USER" --password-stdin
            docker push $REGISTRY/$IMAGE:$TAG
            docker tag $REGISTRY/$IMAGE:$TAG $REGISTRY/$IMAGE:latest
            docker push $REGISTRY/$IMAGE:latest
          '''
        }
      }
    }
    stage('Update K8s Secret + Deploy') {
      steps {
        sh '''
          set -e
          kubectl -n dev create secret generic java17-vault-service-secret --from-literal=APP_SECRET="$(cat vault_secret_value.txt)" --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n dev set image deploy/java17-vault-service app=$REGISTRY/$IMAGE:$TAG
          kubectl -n dev rollout status deploy/java17-vault-service --timeout=180s
        '''
      }
    }
  }
}
